services:
    _defaults:
        autowire: true
        autoconfigure: true

    AlexanderA2\SymfonyDatasheetBundle\:
        resource: '../../'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Tests/'
